### ISSUE TITLE
Question: Why not leader_only on the migrations?

### ISSUE THREAD

**Issue by Kalyse** [oliveradria/symfony-elasticbeanstalk-optimization#1]
https://github.com/oliveradria/symfony-elasticbeanstalk-optimization/blob/master/.ebextensions/symfony.config#L6

I see you run migrations, I'm curious if you happen to know:

1) Why are you not running it on leader_only
2) Is thereany problems in running a migration AND a schema:update (incase a bad bad developer forgot to run a migration differential?)

**Comment by oliveradria** [comment]
Hi! I haven't updated this in a while, when I have a few minutes, I will try to update the package (to Symfony 5).

1. Yes, can be leader only. In this case, it will probably just say "Nothing to migrate" on the non-leaders.
2. I would not advise running schema:update, but rather add the migration as soon as possible. What if Dev A forgot the diff, then Dev B gets the newest branch, does a diff because they updated some schema, then Dev B's diff would have the diff for both Dev A and Dev B changes, and it might fail in production, because Dev A already manually did a schema:update (e.g. something like "Table already exists" might pop up). Better perhaps to do something like doctrine:schema:validate and fail if there's an error.
